// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhn8yjAxfkhs7qE6of1aSclhdtMQxm-w',
    appId: '1:440141123620:web:c352ec4b52b2a939e608b1',
    messagingSenderId: '440141123620',
    projectId: 'loginfirebase-4e3b6',
    authDomain: 'loginfirebase-4e3b6.firebaseapp.com',
    storageBucket: 'loginfirebase-4e3b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhm95KJ0gOTYSHDmxK9D9QbIg-FhpUm7o',
    appId: '1:440141123620:android:b05818c1e0798391e608b1',
    messagingSenderId: '440141123620',
    projectId: 'loginfirebase-4e3b6',
    storageBucket: 'loginfirebase-4e3b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcBYOttYE9zOjilRHRdwDoo2Gtd-iZzaY',
    appId: '1:440141123620:ios:a405779a99a7d2f9e608b1',
    messagingSenderId: '440141123620',
    projectId: 'loginfirebase-4e3b6',
    storageBucket: 'loginfirebase-4e3b6.appspot.com',
    iosClientId: '440141123620-8cs4n1idvnvcubfshiremasnna6stneg.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcBYOttYE9zOjilRHRdwDoo2Gtd-iZzaY',
    appId: '1:440141123620:ios:a405779a99a7d2f9e608b1',
    messagingSenderId: '440141123620',
    projectId: 'loginfirebase-4e3b6',
    storageBucket: 'loginfirebase-4e3b6.appspot.com',
    iosClientId: '440141123620-8cs4n1idvnvcubfshiremasnna6stneg.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageWithFirebase',
  );
}
